### ISSUE TITLE
Create User Registration and Login/Logout

### ISSUE THREAD

**Issue by ianrwhitney** [cs481-ekh/f21-args-n-kwargs#2]
References #3 
As a new user, when I navigate to the home page, I am able to register an account with my email that I can use to login in with. 

Acceptance Criteria
- [x] Given a new user, after I navigate to the home page and click log in, I am prompted to create an account with an email and password. #8 
- [x] Given a new user, when they supply a password, the password meets a security requirement including it is at least 8 characters long, not entirely numeric and not a commonly used password. #8 
- [x] GIven a user, when I supply my password incorrectly, I am have a button on the login in page to recover my password. #7 
- [x] Given a registered user, when I supply my  email and password at login my account  information has been saved to allow me login in. #5
- [x] As an admin, I have the ability to view user accounts and permissions. #4
